services:
  proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - ${TANK_ROOT}/config/proxy-manager/data:/data
      - ${TANK_ROOT}/config/proxy-manager/letsencrypt:/etc/letsencrypt


